openapi: 3.0.3
info:
  title: API di esempio
  version: 1.0.0
paths:
  /user/profile:
    get:
      summary: "[DEPRECATED] Get user profile"
      description: Questo endpoint è deprecato e verrà rimosso nelle prossime versioni.
      operationId: getUserProfile
      tags:
        - User
      deprecated: true
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
          description: ID dell'utente
      responses:
        '200':
          description: Profilo dell'utente restituito con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Utente non trovato
paths:
  /user/settings:
    get:
      summary: " Get user Setting"
      description: Questo endpoint è deprecato e verrà rimosso nelle prossime versioni.
      operationId: getUserSettings
      tags:
        - User
      deprecated: true
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
          description: ID dell'utente
      responses:
        '200':
          description: modifica i parametri
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Utente no

tags:
  - name: User
    description: Operazioni relative agli utenti
